##########################
# APPLE                  #
##########################
# APPLE_DEVELOPER_ID
# The developer ID used for notarization process.
APPLE_DEVELOPER_ID = ""

# APPLE_KEYCHAIN_PROFILE
# The keychain access used for accessing notarization credentials.
APPLE_KEYCHAIN_PROFILE = ""




##########################
# CONTAINER              #
##########################
# CONTAINER_USERNAME
# Use to login your container image's registry's service provider (e.g. Docker,
# GitHub Packages) etc. This is the account username.
CONTAINER_USERNAME = ""


# CONTAINER_PASSWORD
# Use to login your container image's registry's service provider (e.g. Docker,
# GitHub Packages) etc. This is the account password or token value.
CONTAINER_PASSWORD = ""




##########################
# DISTRIBUTION ECOSYSTEM #
##########################
# PROJECT_GPG_ID
# Your GPG ID for signing here. Note that this requires GPG to be installed in
# the system and the secret key is available for performing such transaction.
PROJECT_GPG_ID =""




######################
# GOOGLE AI          #
######################
# GOOGLEAI_API_TOKEN
# This is the authentication API token provided by Google AI using Google AI
# Studio. A token can be procured from:
#     (1) https://aistudio.google.com/ (look for 'Get API Key' button)
#
# Without this token, GOOGLEAI library will not function at all.
GOOGLEAI_API_TOKEN = ''




##########################
# MICROSOFT              #
##########################
# MICROSOFT_CERT
# The cert file for Microsoft Windows' code-signing certifcate use. The format
# can be normal certifcate, SPC, or PKCS12.
MICROSOFT_CERT = ""


# MICROSOFT_CERT_HASH
# The shasum algorithm of the certificate for Microsoft Windows' code-signing
# certifcate use. It can be of the following values:
#   1) 'SHA256'
#   2) 'MD5'
#   3) 'SHA1'
#   4) 'SHA2'
#   5) 'SHA384'
#   6) 'SHA512'
MICROSOFT_CERT_HASH = ""


# MICROSOFT_CERT_TYPE
# The cert type for Microsoft Windows' code-signing certifcate use. It can only
# be the following values:
#   1. 'CERT' - conventional cert format
#   2. 'SPC' - SPC format
#   3. 'PKCS12' - PKCS12 container format
MICROSOFT_CERT_TYPE = ""


# MICROSOFT_CERT_TIMESTAMP
# The URL for sourcing the timestamp used in Microsoft Windows' code-signing
# process. Although specification stated not required, AutomataCI set it as
# compulsory. Known good cert location are:
#   1. http://timestamp.digicert.com
#   2. http://timestamp.sectigo.com
MICROSOFT_CERT_TIMESTAMP = ""


# MICROSOFT_KEYFILE
# The private keyfile for Microsoft Windows' code-signing certifcate use. It is
# optional if MICROSOFT_CERT is a PKCS12 format.
MICROSOFT_CERT_KEYFILE = ""


# MICROSOFT_CERT_PASSWORD
# Private password to unlock the Microsoft Windows' code-signing certifcate and
# private key for signing. Only used with osslsigncode and equivalent usually
# in Notary stage.
MICROSOFT_CERT_PASSWORD = ""




######################
# NPM TECHNOLOGY     #
######################
# NPM_USERNAME
# The username for login.
NPM_USERNAME = ""


# NPM_TOKEN
# The Authentication token (e.g. _authToken) for logging into the corresponding
# NPM registry defined in the CONFIG.toml.
NPM_TOKEN = ""




######################
# PYTHON TECHNOLOGY  #
######################
# TWINE_USERNAME
# Use for logging in a PyPi server. This is the account username. Only used
# when PROJECT_PYTHON is enabled.
TWINE_USERNAME = ""


# TWINE_PASSWORD
# Use for logging in a PyPi server. This is the account password. Only used
# when PROJECT_PYTHON is enabled.
TWINE_PASSWORD = ""




######################
# RUST TECHNOLOGY    #
######################
# CARGO_PASSWORD
# Use for logging in a Cargo registry server. This is the account
# password/secret token. Only used when PROJECT_RUST is enabled.
CARGO_PASSWORD = ""
